### ISSUE TITLE
如何让父节点每次展开的时候都去获取最新的数据， 都执行load呢？

### ISSUE THREAD

**Issue by Lee-42** [wsfe/ctree#100]
**问题描述**
如何让父节点每次展开的时候都去获取最新的数据， 都执行load呢？
我发现使用异步加载方法只会在第一次展开的时候执行，执行之后节点的loaded会被设为true，之后收起再展开的时候不会再次执行异步加载方法，那如果我下一次展开的时候不就不能获取最新的子节点数据了吗？还是说有别的方式可以让它执行

**组件版本**
 - Vue3
 - @wsfe/vue-tree
![1](https://github.com/user-attachments/assets/1a21f8d5-9e77-4040-b060-9c3208a790ca)

**Comment by ChuChencheng** [comment]
可以试试新版的 `updateNode` 呢

`_loaded` 只负责标记第一次把子节点加载进来，确实没有考虑重复加载
