### ISSUE TITLE
提个优化项。this.$refs.tree.setCheckedKeys

### ISSUE THREAD

**Issue by ginkosen** [wsfe/ctree#19]
this.$refs.tree.setCheckedKeys 选中的key是我明确知道的。不应该再触发checked-change事件

**Comment by ChuChencheng** [comment]
checked-change 传出去的参数包括了完整的节点信息，里面不止有选中的 key 。

如果在 setCheckedKeys 之后不触发 checked-change ，算是个 breaking change 吧，不太好直接改。

我认为这应该算是个设计缺陷，之前不应该挂太多方法在 $refs 上的 😂

**Comment by ginkosen** [comment]
恩。
明白。目前我只能增加一个true/false的状态来控制丢弃通过setCheckedKeys设定的选中节点

**Comment by zhengsky1** [comment]
能兼容下ie11嘛

**Comment by zhengsky1** [comment]
ie11堆栈溢出，我不确定是不是递归引起的
