### ISSUE TITLE
ie11 堆栈溢出 

### ISSUE THREAD

**Issue by zhengsky1** [wsfe/ctree#25]
IE11浏览器打开，堆栈溢出，不清楚是不是过多的函数调用引起的

**Comment by zhengsky1** [comment]
使用ie11打开，报错‘对象不支持“assign”属性或方法‘，我使用了babel-polyfil，就发现ie11报堆栈溢出了，想问下是我其他地方没配好吗

**Comment by ChuChencheng** [comment]
请问浏览器具体是哪个版本，以及具体的报错信息是什么，最好能有个复现的步骤

**Comment by zhengsky1** [comment]
1. 浏览器版本:IE11,vue版本：2.6.11 
2. 我在IE11浏览器打开[github在线demo链接](https://wsfe.github.io/ctree)，报错：SCRIPT438: 对象不支持“assign”属性或方法，
3. 在我的项目里面引入插件在IE11浏览器会报错：SCRIPT28: 堆栈溢出及SCRIPT2343: 堆栈溢出，位置: 第 1 行，
4. 我的项目里面引入了ant 插件，`import 'core-js/stable'    import 'regenerator-runtime/runtime'` 用这两个作了IE11浏览器的兼容
5. 为了测试我加上`import '@babel/polyfill'`作兼容同样报错：SCRIPT28: 堆栈溢出及SCRIPT2343: 堆栈溢出，位置: 第 1 行

**Comment by ChuChencheng** [comment]
我身边暂时没有条件安装 IE11 ，抱歉

我搜了一下，推测有两种可能：

1. polyfill 的问题
https://stackoverflow.com/questions/56564198/out-of-stack-space-in-internet-explorer-11-for-angular-app-when-integrated-into
https://stackoverflow.com/questions/38931917/out-of-stack-space-error-in-ie11-when-using-aureliajs-and-babel-polyfill

2. 数组长度过大， IE 不支持
https://segmentfault.com/q/1010000022975347
