### ISSUE TITLE
组件不错，名字不好，不利于检索，可以改一下

### ISSUE THREAD

**Issue by Tilang** [wsfe/ctree#31]

**Comment by M69W** [comment]
我是 通过 [npm 搜索 vue tree找到](https://www.npmjs.com/search?q=vue%20tree) , 
感觉是 vue-tree 被用了
在 npm 上显示 [custom-ctree](https://www.npmjs.com/package/custom-ctree) 倒是比较好理解 ctree

**Comment by ChuChencheng** [comment]
取名字真的挺难的哈哈
custom-ctree 不知道是哪位老哥把这个仓库又上传了一遍😂

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/172976028-e73f738f-8ffa-403a-bcb9-3788668e7f38.png)


另外一个 删除了吗？
https://www.npmjs.com/package/@wsfe/ctree
https://www.npmjs.com/package/custom-ctree

**Comment by andy3213** [comment]
@ChuChencheng 老哥们，我看这版本改名称vue-tree了，上一版的Ctree能否无缝升级到vue-tree ? 是否需要改动我的代码？

**Comment by ChuChencheng** [comment]
> @ChuChencheng 老哥们，我看这版本改名称vue-tree了，上一版的Ctree能否无缝升级到vue-tree ? 是否需要改动我的代码？

原先的 `@wsfe/ctree` 包并没有发布新版本，可以继续使用。 

新的版本主要是做了 vue3 的适配，是一个新的 npm 包 `@wsfe/vue-tree` 。

从 PR 上来看， `@wsfe/vue-tree` 没有新增功能，如果是 vue2 项目，可不升级。

@angrytoro 有关 `@wsfe/ctree` 升级到 `@wsfe/vue-tree` 是否有升级文档说明？
