### ISSUE TITLE
多选的时候，子级不全选，选部分，怎么能取到父级的半选中状态数据

### ISSUE THREAD

**Issue by javascript666666** [wsfe/ctree#37]
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/25980255/188851499-207930bb-a5b7-4518-a506-498421473b12.png">

**Comment by ChuChencheng** [comment]
![image](https://user-images.githubusercontent.com/9395932/188865556-a5923eda-4061-40d1-831b-25c66ae37f82.png)

可以尝试调用这个方法哈

**Comment by javascript666666** [comment]
> ![image](https://user-images.githubusercontent.com/9395932/188865556-a5923eda-4061-40d1-831b-25c66ae37f82.png)
> 
> 可以尝试调用这个方法哈

获取使用这个方法可以了， 再请教一下，如果是这个数据， 反显只显示半选状态，不是全选状态，有方法吗？还是只能按照id去过滤了

**Comment by javascript666666** [comment]
按照id规律过滤了
