### ISSUE TITLE
如何自定义节点的渲染内容

### ISSUE THREAD

**Issue by fangchao1004** [wsfe/ctree#41]
![image](https://user-images.githubusercontent.com/33364305/210527725-d08b67fb-86bf-4343-89e6-274520437577.png)
只看到一个render属性，要求是一个function，但是vue不像react那样可以在函数中返回node节点。请问有具体的解决方案吗？

**Comment by ChuChencheng** [comment]
vue 是可以返回 JSX 的，可以参考这个例子：https://github.com/wsfe/ctree/blob/dev/examples/InsertRenderTree.vue
以及 vue2 文档：https://v2.cn.vuejs.org/v2/guide/render-function.html#JSX

**Comment by fangchao1004** [comment]
谢谢大佬
