### ISSUE TITLE
vue-cli新创建的项目咋集成不进来呢

### ISSUE THREAD

**Issue by hu2014** [wsfe/ctree#45]
如题

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/232461882-ac63a53a-3846-4775-ab75-5427a7add064.png)

**Comment by ChuChencheng** [comment]
从报错信息看，可以尝试给 webpack 配置一下处理 `.mjs` 文件的 loader

可以试试看给 `vue.config.js` 加上这个配置

```javascript
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto"
        }
      ]
    }
  }
}
```

**Comment by ChuChencheng** [comment]
不知道你用的 vue-cli 或者 webpack 版本是什么呢

**Comment by hu2014** [comment]
vue-cli 4.5版本

**Comment by hu2014** [comment]
哦。点击父节点，自动展开能关闭吗？只能通过点击小图标展开收起

**Comment by hu2014** [comment]
还有个问题是，这个想要自定义图标怎么添加呢

**Comment by ChuChencheng** [comment]
目前没有支持关闭 “点击节点标题展开” 这个特性。但是如果有设置 `selectable` 或 `checkable` ，点击标题就不会展开或收起了 

自定义图标可以通过 `render` 自定义节点添加

**Comment by hu2014** [comment]
好的，谢谢。我就是觉得在触发双击事件的时候，那个节点会自动展开下级然后关闭有点奇怪。看能否将这个特性开出来可供关闭。另外双击事件那里,触发双击事件的时候，单击事件会触发两次，然后触发双击事件。

**Comment by hu2014** [comment]
1.设置了 selectable 后，点击节点不会自动展开了。
2.将项目拉下来，重写了双击事件，第二次单击事件不会触发，只会触发第一次的单击事件和双击事件
