### ISSUE TITLE
组件没有销毁方法，导致内存一直下不去

### ISSUE THREAD

**Issue by hu2014** [wsfe/ctree#49]
组件内部使用的变量，在组件销毁后，还一直存在，导致应用占用内存一直很高

**Comment by ChuChencheng** [comment]
应该会自动垃圾回收吧，能麻烦给个示例么

**Comment by hu2014** [comment]
<template>
  <div class="container">
    <div class="tree">
      <CTree
        ref="tree"
        :data="treeData"
        checkable
        selectable
      ></CTree>
    </div>
    <div class="control">
      <div class="desc-block">
        <p>说明：在 Chrome 下表现良好</p>
        <p>在火狐浏览器下，因为其异步滚动策略 (scroll-linked) ，在快速滚动时会导致内容空白。</p>
        <p>另：浏览器元素/文档是有最大高度限制的，过多数据会导致显示不正常(Chrome 下 100 万条可以正常显示，但是在火狐或 Edge 则不行)</p>
      </div>
      <div class="controls">
        <label>节点深度：</label>
        <input
          v-model="params.treeDepth"
          type="number"
        >
      </div>
      <div class="controls">
        <label>每层节点个数：</label>
        <input
          v-model="params.nodesPerLevel"
          type="number"
        >
      </div>
      <div class="controls">
        <label>总节点个数：</label>
        {{ nodeTotal }}
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleGenerate">生成树节点数据</button>
          <button @click="handleGenerateTotal('1w')">1w 节点</button>
          <button @click="handleGenerateTotal('10w')">10w 节点</button>
          <button @click="handleGenerateTotal('20w')">20w 节点</button>
          <button @click="handleGenerateTotal('30w')">30w 节点</button>
        </div>
        <div class="actions">
          <button @click="handleBigTree">生成大数据</button>
          <button @click="handleSetData">设置树数据</button>
        </div>
        <div class="actions">
          <span v-if="!isTreeSet" style="color: red;">树数据已生成</span>
          <span v-else  style="color: green;">树数据已设置</span>
        </div>
      </div>
      <div class="controls">
        <label>滚动节点id：</label>
        <input
          v-model="scrollKey"
          type="text"
        />
      </div>
      <div class="controls">
        <label>滚动垂直位置：</label>
        <select v-model="scrollVerticalOption">
          <option value="top">top</option>
          <option value="center">center</option>
          <option value="bottom">bottom</option>
        </select>
      </div>
      <div class="controls">
        <label>滚动垂直偏移值：</label>
        <input
          v-model.number="scrollValue"
          type="text"
        />
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleScrollToNode">滚动到此节点</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CTree from '@'
import treeDataGenerator from '../tests/tree-data-generator'

const dataAmountMap = {
  '1w': {
    treeDepth: 2,
    nodesPerLevel: 100,
  },
  '10w': {
    treeDepth: 2,
    nodesPerLevel: 320,
  },
  '20w': {
    treeDepth: 2,
    nodesPerLevel: 450,
  },
  '30w': {
    treeDepth: 2,
    nodesPerLevel: 550,
  },
}

let cache = []

export default {
  name: 'Performance',
  components: {
    CTree,
  },
  data () {
    return {
      cache: [],
      isTreeSet: false,
      params: {
        treeDepth: 2,
        nodesPerLevel: 5,
      },
      nodeTotal: 0,
      treeData: [],
      scrollKey: '',
      scrollVerticalOption: 'top',
      scrollValue: 0,
    }
  },
  methods: {
    handleGenerate () {
      const mock = treeDataGenerator(Object.assign({}, this.params, { inOrder: true, sameIdTitle: true, forceString: true }))
      cache = mock.data
      this.nodeTotal = mock.total
      this.isTreeSet = false
    },
    handleGenerateTotal (amount) {
      Object.assign(this.params, dataAmountMap[amount])
      this.handleGenerate()
    },
    handleSetData () {
      // this.treeData = cache.concat()
      /** 性能模式 */
      this.$refs.tree.setData(cache.concat())
      this.isTreeSet = true
    },
    handleScrollToNode () {
      this.$refs.tree.scrollTo(this.scrollKey, this.scrollValue || this.scrollVerticalOption)
    },
    //调试
    handleBigTree(){
      const data = [],
      root = 3,
      children = 1,
      base = 800000;
      for (let i = 0; i < root; i++) {
        data.push({
          id: `${i}`,
          title: `test-${i}`,
          children: [],
        });
        for (let j = 0; j < children; j++) {
          data[i].children.push({
            id: `${i}-${j}`,
            title: `test-${i}-${j}`,
            children: [],
          });
          for (let k = 0; k < base; k++) {
            data[i].children[j].children.push({
              id: `${i}-${j}-${k}`,
              title: `test-${i}-${j}-${k}`,
            });
          }
        }
        }
        cache = data
      }
  },
  created () {
    this.handleGenerate()
  },
}
</script>

<style lang="less" scoped>
.container {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  .tree {
    flex: 2;
  }
  .control {
    flex: 1;
    padding: 30px 0;
    border-left: 1px solid gray;
    .desc-block {
      padding: 10px 30px;
      margin-bottom: 20px;
    }
    .controls {
      @left-len: 120px;

      padding: 10px;
      label {
        display: inline-block;
        width: @left-len;
        text-align: right;
      }
      .actions {
        margin-left: @left-len;
        margin-bottom: 10px;
        button {
          cursor: pointer;
          margin-right: 10px;
        }
      }
    }
  }
}
</style>

**Comment by hu2014** [comment]
代码里面的examples实例我修改了以下Performance页面，点击 生成大数据 然后渲染树形后，切换到别的页面没有树形的页面，内存一直没变化

**Comment by hu2014** [comment]
<template>
  <div class="container">
    <div class="tree">
      <CTree
        ref="tree"
        :data="treeData"
        checkable
        selectable
      ></CTree>
    </div>
    <div class="control">
      <div class="desc-block">
        <p>说明：在 Chrome 下表现良好</p>
        <p>在火狐浏览器下，因为其异步滚动策略 (scroll-linked) ，在快速滚动时会导致内容空白。</p>
        <p>另：浏览器元素/文档是有最大高度限制的，过多数据会导致显示不正常(Chrome 下 100 万条可以正常显示，但是在火狐或 Edge 则不行)</p>
      </div>
      <div class="controls">
        <label>节点深度：</label>
        <input
          v-model="params.treeDepth"
          type="number"
        >
      </div>
      <div class="controls">
        <label>每层节点个数：</label>
        <input
          v-model="params.nodesPerLevel"
          type="number"
        >
      </div>
      <div class="controls">
        <label>总节点个数：</label>
        {{ nodeTotal }}
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleGenerate">生成树节点数据</button>
          <button @click="handleGenerateTotal('1w')">1w 节点</button>
          <button @click="handleGenerateTotal('10w')">10w 节点</button>
          <button @click="handleGenerateTotal('20w')">20w 节点</button>
          <button @click="handleGenerateTotal('30w')">30w 节点</button>
        </div>
        <div class="actions">
          <button @click="handleBigTree">生成大数据</button>
          <button @click="handleSetData">设置树数据</button>
        </div>
        <div class="actions">
          <span v-if="!isTreeSet" style="color: red;">树数据已生成</span>
          <span v-else  style="color: green;">树数据已设置</span>
        </div>
      </div>
      <div class="controls">
        <label>滚动节点id：</label>
        <input
          v-model="scrollKey"
          type="text"
        />
      </div>
      <div class="controls">
        <label>滚动垂直位置：</label>
        <select v-model="scrollVerticalOption">
          <option value="top">top</option>
          <option value="center">center</option>
          <option value="bottom">bottom</option>
        </select>
      </div>
      <div class="controls">
        <label>滚动垂直偏移值：</label>
        <input
          v-model.number="scrollValue"
          type="text"
        />
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleScrollToNode">滚动到此节点</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CTree from '@'
import treeDataGenerator from '../tests/tree-data-generator'

const dataAmountMap = {
  '1w': {
    treeDepth: 2,
    nodesPerLevel: 100,
  },
  '10w': {
    treeDepth: 2,
    nodesPerLevel: 320,
  },
  '20w': {
    treeDepth: 2,
    nodesPerLevel: 450,
  },
  '30w': {
    treeDepth: 2,
    nodesPerLevel: 550,
  },
}

let cache = []

export default {
  name: 'Performance',
  components: {
    CTree,
  },
  data () {
    return {
      cache: [],
      isTreeSet: false,
      params: {
        treeDepth: 2,
        nodesPerLevel: 5,
      },
      nodeTotal: 0,
      treeData: [],
      scrollKey: '',
      scrollVerticalOption: 'top',
      scrollValue: 0,
    }
  },
  methods: {
    handleGenerate () {
      const mock = treeDataGenerator(Object.assign({}, this.params, { inOrder: true, sameIdTitle: true, forceString: true }))
      cache = mock.data
      this.nodeTotal = mock.total
      this.isTreeSet = false
    },
    handleGenerateTotal (amount) {
      Object.assign(this.params, dataAmountMap[amount])
      this.handleGenerate()
    },
    handleSetData () {
      // this.treeData = cache.concat()
      /** 性能模式 */
      this.$refs.tree.setData(cache.concat())
      this.isTreeSet = true
    },
    handleScrollToNode () {
      this.$refs.tree.scrollTo(this.scrollKey, this.scrollValue || this.scrollVerticalOption)
    },
    //调试
    handleBigTree(){
      const data = [],
      root = 3,
      children = 1,
      base = 800000;
      for (let i = 0; i < root; i++) {
        data.push({
          id: `${i}`,
          title: `test-${i}`,
          children: [],
        });
        for (let j = 0; j < children; j++) {
          data[i].children.push({
            id: `${i}-${j}`,
            title: `test-${i}-${j}`,
            children: [],
          });
          for (let k = 0; k < base; k++) {
            data[i].children[j].children.push({
              id: `${i}-${j}-${k}`,
              title: `test-${i}-${j}-${k}`,
            });
          }
        }
        }
        cache = data
      }
  },
  created () {
    this.handleGenerate()
  },
}
</script>

<style lang="less" scoped>
.container {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  .tree {
    flex: 2;
  }
  .control {
    flex: 1;
    padding: 30px 0;
    border-left: 1px solid gray;
    .desc-block {
      padding: 10px 30px;
      margin-bottom: 20px;
    }
    .controls {
      @left-len: 120px;

      padding: 10px;
      label {
        display: inline-block;
        width: @left-len;
        text-align: right;
      }
      .actions {
        margin-left: @left-len;
        margin-bottom: 10px;
        button {
          cursor: pointer;
          margin-right: 10px;
        }
      }
    }
  }
}
</style>

**Comment by hu2014** [comment]
`<template>
  <div class="container">
    <div class="tree">
      <CTree
        ref="tree"
        :data="treeData"
        checkable
        selectable
      ></CTree>
    </div>
    <div class="control">
      <div class="desc-block">
        <p>说明：在 Chrome 下表现良好</p>
        <p>在火狐浏览器下，因为其异步滚动策略 (scroll-linked) ，在快速滚动时会导致内容空白。</p>
        <p>另：浏览器元素/文档是有最大高度限制的，过多数据会导致显示不正常(Chrome 下 100 万条可以正常显示，但是在火狐或 Edge 则不行)</p>
      </div>
      <div class="controls">
        <label>节点深度：</label>
        <input
          v-model="params.treeDepth"
          type="number"
        >
      </div>
      <div class="controls">
        <label>每层节点个数：</label>
        <input
          v-model="params.nodesPerLevel"
          type="number"
        >
      </div>
      <div class="controls">
        <label>总节点个数：</label>
        {{ nodeTotal }}
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleGenerate">生成树节点数据</button>
          <button @click="handleGenerateTotal('1w')">1w 节点</button>
          <button @click="handleGenerateTotal('10w')">10w 节点</button>
          <button @click="handleGenerateTotal('20w')">20w 节点</button>
          <button @click="handleGenerateTotal('30w')">30w 节点</button>
        </div>
        <div class="actions">
          <button @click="handleBigTree">生成大数据</button>
          <button @click="handleSetData">设置树数据</button>
        </div>
        <div class="actions">
          <span v-if="!isTreeSet" style="color: red;">树数据已生成</span>
          <span v-else  style="color: green;">树数据已设置</span>
        </div>
      </div>
      <div class="controls">
        <label>滚动节点id：</label>
        <input
          v-model="scrollKey"
          type="text"
        />
      </div>
      <div class="controls">
        <label>滚动垂直位置：</label>
        <select v-model="scrollVerticalOption">
          <option value="top">top</option>
          <option value="center">center</option>
          <option value="bottom">bottom</option>
        </select>
      </div>
      <div class="controls">
        <label>滚动垂直偏移值：</label>
        <input
          v-model.number="scrollValue"
          type="text"
        />
      </div>
      <div class="controls">
        <div class="actions">
          <button @click="handleScrollToNode">滚动到此节点</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CTree from '@'
import treeDataGenerator from '../tests/tree-data-generator'

const dataAmountMap = {
  '1w': {
    treeDepth: 2,
    nodesPerLevel: 100,
  },
  '10w': {
    treeDepth: 2,
    nodesPerLevel: 320,
  },
  '20w': {
    treeDepth: 2,
    nodesPerLevel: 450,
  },
  '30w': {
    treeDepth: 2,
    nodesPerLevel: 550,
  },
}

let cache = []

export default {
  name: 'Performance',
  components: {
    CTree,
  },
  data () {
    return {
      cache: [],
      isTreeSet: false,
      params: {
        treeDepth: 2,
        nodesPerLevel: 5,
      },
      nodeTotal: 0,
      treeData: [],
      scrollKey: '',
      scrollVerticalOption: 'top',
      scrollValue: 0,
    }
  },
  methods: {
    handleGenerate () {
      const mock = treeDataGenerator(Object.assign({}, this.params, { inOrder: true, sameIdTitle: true, forceString: true }))
      cache = mock.data
      this.nodeTotal = mock.total
      this.isTreeSet = false
    },
    handleGenerateTotal (amount) {
      Object.assign(this.params, dataAmountMap[amount])
      this.handleGenerate()
    },
    handleSetData () {
      // this.treeData = cache.concat()
      /** 性能模式 */
      this.$refs.tree.setData(cache.concat())
      this.isTreeSet = true
    },
    handleScrollToNode () {
      this.$refs.tree.scrollTo(this.scrollKey, this.scrollValue || this.scrollVerticalOption)
    },
    //调试
    handleBigTree(){
      const data = [],
      root = 3,
      children = 1,
      base = 800000;
      for (let i = 0; i < root; i++) {
        data.push({
          id: `${i}`,
          title: `test-${i}`,
          children: [],
        });
        for (let j = 0; j < children; j++) {
          data[i].children.push({
            id: `${i}-${j}`,
            title: `test-${i}-${j}`,
            children: [],
          });
          for (let k = 0; k < base; k++) {
            data[i].children[j].children.push({
              id: `${i}-${j}-${k}`,
              title: `test-${i}-${j}-${k}`,
            });
          }
        }
        }
        cache = data
      }
  },
  created () {
    this.handleGenerate()
  },
}
</script>

<style lang="less" scoped>
.container {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  .tree {
    flex: 2;
  }
  .control {
    flex: 1;
    padding: 30px 0;
    border-left: 1px solid gray;
    .desc-block {
      padding: 10px 30px;
      margin-bottom: 20px;
    }
    .controls {
      @left-len: 120px;

      padding: 10px;
      label {
        display: inline-block;
        width: @left-len;
        text-align: right;
      }
      .actions {
        margin-left: @left-len;
        margin-bottom: 10px;
        button {
          cursor: pointer;
          margin-right: 10px;
        }
      }
    }
  }
}
</style>
`

**Comment by hu2014** [comment]
[](url)G:\workFile\persion\vue-tree\examples\Performance.vue

**Comment by hu2014** [comment]
handleBigTree(){
      const data = [],
      root = 3,
      children = 1,
      base = 800000;
      for (let i = 0; i < root; i++) {
        data.push({
          id: `${i}`,
          title: `test-${i}`,
          children: [],
        });
        for (let j = 0; j < children; j++) {
          data[i].children.push({
            id: `${i}-${j}`,
            title: `test-${i}-${j}`,
            children: [],
          });
          for (let k = 0; k < base; k++) {
            data[i].children[j].children.push({
              id: `${i}-${j}-${k}`,
              title: `test-${i}-${j}-${k}`,
            });
          }
        }
        }
        cache = data
      }

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/234765635-e02881f2-8322-4b7b-8699-2cec4c350544.png)

**Comment by ChuChencheng** [comment]
折腾了一番，感觉是 Vue 切换 component is 的问题，因为 Performance 页面包含了个原生的 select ，所以内存没法被释放。

做了个不含树组件的仓库来复现（Vue3）：https://github.com/ChuChencheng/vue-memory-leak
记得要把 Vue.js devtools 关了，貌似这个也会有影响。

https://github.com/wsfe/vue-tree/assets/9395932/d4bca167-8415-42da-8621-f99c2ccc27ee

对比内存快照，发现多了游离的 DOM 节点
<img width="504" alt="image" src="https://github.com/wsfe/vue-tree/assets/9395932/819e4db9-b9f3-4b8a-b422-923d9c836ab5">

同时在本项目的 2.x 分支（Vue2） Example 中做了类似的改动，有同样的问题。

具体是什么问题，得看 Vue 源码了，毕竟[官网](https://cn.vuejs.org/guide/essentials/component-basics.html#dynamic-components)明确写了切换 component 会卸载之前的组件。
官方 [issue](https://github.com/vuejs/core/issues?q=memory+leak) 里也有一些类似的问题还没解决的样子。

**Comment by hu2014** [comment]
![image](https://github.com/wsfe/vue-tree/assets/36222808/d4b497a0-d29d-446f-b743-59a84c15fe8e)
我通过在Tree.vue 文件中的销毁方法中手动添加了销毁，解决了内存没变化的问题。由于我TS不熟，手动赋值null,导致与上面定义的类型不一致，该文件中需要所有涉及到的地方添加非空断言！，作者大大看一下有没有别的好的写法。

**Comment by ChuChencheng** [comment]
缓解了内存占用的情况

Vue2 版本 `@wsfe/ctree` v2.3.1
Vue2/3 通用版本 `@wsfe/vue-tree` v3.0.3
