### ISSUE TITLE
TreeDrop单选时报错

### ISSUE THREAD

**Issue by ROYIANS** [wsfe/ctree#55]
![image](https://github.com/wsfe/vue-tree/assets/25497779/113ff32e-8a63-418e-9446-833f4c1092fe)
![image](https://github.com/wsfe/vue-tree/assets/25497779/2ab418bc-8a37-4e1c-9214-34759b9613cd)
原因是$refs.treeRef 就不是RefImpl对象了，不需要.value，直接.titleField就好了

**Comment by ChuChencheng** [comment]
已修复，可在在线 Demo Drop 页签验证 😀
