### ISSUE TITLE
check和uncheck事件触发时，会先触发check事件

### ISSUE THREAD

**Issue by hybzhl** [wsfe/ctree#65]
例如我要触发uncheck事件触发时，组件会先触发check事件，然后再触发uncheck事件，select和unselect同理
示例代码：
  <div id="IndexTree" class="IndexTree">
    <div class="IndexTree_Contern" :style="treeHeight">
      <VTreeSearch
        ref="comIndexTree"
        emptyText="目录树无内容"
        searchPlaceholder="搜索目录树内容"
        :showCheckAll="false"
        :showCheckedButton="false"
        :loading="treeLoading"
        :checkable="true"
        :selectable="true"
        :value="selectValue"
        :data="list"
        @check="treeCheck"
        @uncheck="treeUncheck"
        @select="treeSelect"
        @unselect="treeUnselect"
      />
    </div>
  </div>
<script setup>
// 树节点选择
const treeSelect = (node) => {
 console.log('触发选中')
}
// 树节点取消选择
const treeUnselect = (node) => {
   console.log('触发取消选中')
}
// 树选中
const treeCheck =(node) => {
  console.log('true')
}
// 树取消选中
const treeUncheck = (node) => {
  console.log('false')
}
</script>

**Comment by hybzhl** [comment]
<template>
  <div id="IndexTree" class="IndexTree">
    <div class="IndexTree_Contern" :style="treeHeight">
      <VTreeSearch
        ref="comIndexTree"
        emptyText="目录树无内容"
        searchPlaceholder="搜索目录树内容"
        :showCheckAll="false"
        :showCheckedButton="false"
        :loading="treeLoading"
        :checkable="true"
        :selectable="true"
        :value="selectValue"
        :data="list"
        @check="treeCheck"
        @uncheck="treeUncheck"
        @select="treeSelect"
        @unselect="treeUnselect"
      />
    </div>
  </div>
</template>

**Comment by ChuChencheng** [comment]
没看懂想问什么，请清晰描述问题，想要达到什么效果，实际是什么效果，并提供可复现的示例
