### ISSUE TITLE
节点当前行高亮样式建议

### ISSUE THREAD

**Issue by xtuer** [wsfe/ctree#70]
如图所示，如果能高亮节点所在完整的行就好了。

<img width="463" alt="SCR-20230831-jjlw" src="https://github.com/wsfe/vue-tree/assets/13594346/753ceb2c-7467-45a2-9ab8-2a3f27676f15">

**Comment by ChuChencheng** [comment]
实际上 Tree 有个 `usePadding` prop 没有开放出来，有需要可以先用着

**Comment by xtuer** [comment]
> 实际上 Tree 有个 `usePadding` prop 没有开放出来，有需要可以先用着

谢谢非常好用，使用后可以实现下面的样式了:

<img width="249" alt="SCR-20230909-hwtp" src="https://github.com/wsfe/vue-tree/assets/13594346/1b5e8ee1-f5c1-4d58-955f-f014a974c7a8">

**Comment by ChuChencheng** [comment]
`usePadding` 已废弃，目前直接用的 padding
