### ISSUE TITLE
vue2.x下使用VTreeDrop报错

### ISSUE THREAD

**Issue by nieyuyao** [wsfe/ctree#73]
**Bug 描述**

`vue 2.6.14`下，使用`VTreeDrop`组件发生报错

**复现步骤**

https://stackblitz.com/edit/vitejs-vite-z2qafx?file=src%2Fmain.js,src%2FTreeDemo.vue,package.json,src%2FTreeDrop.vue

> 可以将stackblitz下载到本地，不清楚为什么stackblitz上会报错，会检测成vue3

**期望表现**

没有报错

**实际表现**
<img width="708" alt="image" src="https://github.com/wsfe/vue-tree/assets/17698194/9fb9ebfc-bbc6-491d-b6fe-c75eb9e7e7b9">

**组件版本**
 - Vue: 2.6.14
 - @wsfe/vue-tree: 3.1.0

**额外信息**

None

**Comment by ChuChencheng** [comment]
查了下是 vue2 vue3 兼容的问题，类似还有 `v-model` 在 vue2 也不能用， vue2 里的 `$listeners` 也没法正常使用。
建议 vue2 项目还是用 `@wsfe/ctree` 这个包吧。

https://juejin.cn/post/7236184868480663589#heading-7
