### ISSUE TITLE
两点建议

### ISSUE THREAD

**Issue by zhoushengdong** [wsfe/ctree#79]
Vue2版本的控件功能API十分强大，因为在vue2的各大UI库中的树形控件都没有虚拟滚动的功能，这个组件完美解决了vue2在中后台大数据量树形控件的问题，感谢作者的开源！

使用下来基本业务需求都能涵盖，不过提两点可以优化的UI建议，仅针对于vue2，因为现在vue3的UI库树形控件基本都支持了大数据量以及一些常见的业务需求：

**问题描述**
1.增加展开/折叠的动画过渡效果
2.增加节点之间带连接线的树

**组件版本**
 - Vue2 @wsfe/ctree

**Comment by ChuChencheng** [comment]
@wsfe/ctree v2.4.0
@wsfe/vue-tree v4.0.0
