### ISSUE TITLE
vue2.7 reactive([]) has warning

### ISSUE THREAD

**Issue by defghy** [wsfe/ctree#82]
**Bug 描述**
![image](https://github.com/wsfe/vue-tree/assets/5386958/014277f9-d002-4ceb-a64a-8d832a3e6482)

**组件版本**
 - Vue: 2.7.16
 - @wsfe/vue-tree:  3.2.0

**Comment by ChuChencheng** [comment]
看了下报错，用了 `reactive([])` 的变量无法在 `watch` 中被追踪，目前代码里用到的是 `unloadCheckedNodes` ，这个变量没有在 `watch` 中出现，所以暂时不会引起问题。

有机会下个版本顺手修了。
