### ISSUE TITLE
报错无法使用

### ISSUE THREAD

**Issue by shadowMing** [wsfe/ctree#86]
1. import '@wsfe/vue-tree/style.css'       css文件引入路径有误
2. 报错如图：
![Snipaste_2024-03-15_16-00-51](https://github.com/wsfe/vue-tree/assets/36950573/97c78221-15df-4f8c-9725-3609433bb61c)

**Comment by ChuChencheng** [comment]
麻烦看看 webpack 配置是否有支持 mjs 的 loader 呢
