### ISSUE TITLE
关于 @wsfe/vue-tree 对 Vue2 支持的讨论

### ISSUE THREAD

**Issue by ChuChencheng** [wsfe/ctree#87]
官方在 2023 年 12 月 31 日 [停止了 Vue2 的支持](https://v2.cn.vuejs.org/eol/) ，不再有后续更新。

本树组件原本预想通过 `vue-demi` 库同时兼容 Vue2, Vue3 ，但自发布 @wsfe/vue-tree 3.x 以来，不时会收到一些 Vue2 兼容性相关的 issue ， Vue2, Vue3 的割裂带来的[问题](https://juejin.cn/post/7236184868480663589)远比预想的多。

开这个 issue 有两个目的：

1. 调查用户使用的版本。请留下您目前正在使用的 Vue 版本与树组件版本，有以下三个选项：
  - Vue2 & @wsfe/ctree
  - Vue2 & @wsfe/vue-tree
  - Vue3 & @wsfe/vue-tree
2. 讨论对 Vue2 的支持。是否要停止 `@wsfe/vue-tree` 对 Vue2 的支持，或者有其他同时支持 Vue2, Vue3 的方案。

**Comment by kawais** [comment]
我觉得支持2.7就行了，更早的版本用ctree吧

**Comment by mypkq** [comment]
1、目前使用的版本：Vue3 & @wsfe/vue-tree
2、关于树组件对于vue不同版本的支持，个人倾向于单一支持，即不同组件各自支持vue2或vue3，这样更有利于组件后续的完善

**Comment by ChuChencheng** [comment]
2.7 有啥特别的地方么

我最近把组件用 Vue3 重写了一遍 #92，用到了一些 Vue3 新增的宏，vue-demi 看起来维护也不是很积极，不知道适配情况怎么样
但随着 Vue3 的迭代，新特性肯定会越来越多

我觉得出个大版本移除对 Vue2 的支持吧：

Vue3: @wsfe/vue-tree 4.x
Vue2: @wsfe/ctree 2.x

这样，3.x 就当是个过渡版本了，后面如果有新功能优先加到 @wsfe/vue-tree 4.x 上

这么处理如何？

**Comment by ChuChencheng** [comment]
> Vue3: @wsfe/vue-tree 4.x
> Vue2: @wsfe/ctree 2.x

暂时先这么决定吧，3.x 解决 #88 跟 `setExpand` 性能问题之后，就不加功能上去了
预计 4.x less 变量跟 css 前缀也会从 ctree 统一换成 vtree

**Comment by ChuChencheng** [comment]
Vue2: @wsfe/ctree v2.4.0
Vue3: @wsfe/vue-tree v4.0.0

新版本已发布
