### ISSUE TITLE
能否增加拖动前判断函数

### ISSUE THREAD

**Issue by kawais** [wsfe/ctree#90]
如beforeDragMethod，返回true表示可拖动，false不可拖动
就像beforeDropMethod那样

**Comment by ChuChencheng** [comment]
`dragstart` 事件里面执行 `event.preventDefault()` 的话感觉可行

**Comment by ChuChencheng** [comment]
或者你可以试试监听 `node-dragstart` 事件？里面就有节点信息跟 `DragEvent` 参数

**Comment by ChuChencheng** [comment]
参考[这个](https://wsfe.github.io/vue-tree/playground#eNqlVl1v2jAU/StWXgAJkhUqTWJQsa192B62aa32slRTllzAzHEs26FMiP++6ziEfDUrFCFi32Ofe3wEPuyd90K42xScqTPTEAsWaLjxOSGzHw8SgEyjQAdz3zEP3yHhGsI/wW8GJJLBapWPEiGy0YInEYwMonQgNW5bBzxicIuVe1NBBg/ZZ16pFU5VKKnQRIFOBWEBX+FOrXwHURqLRGqyJxKW5ECWMolJD/X2CsjqtMDiSS3BQ3iksYhrfB4mXGlS00HmpG+0DglsgesBmd+QvTk1XVrApRGZz+ekl53oqjewMLHrXSGz5y0sg5Tp/sBgB5/j+9jQ+IVdUHX/p0Hz7ZpqBtOCdmirNGqUwjVlkQQ+Jdl288opmjSnXTWyKtBCWaNto65yNBrU4UNl9j/ucTd3DT6Pe9LNXYPL3I/F+FR93vyKyHKPCnCR+eNu8xvwOQaNu81vwJcbVHG63KMCXGTQpNugBnyOQZNugxpwt0G2Ymdtd0FBdupRlM64C2pfiRLZq+8CZOhyuwV+udtmc4fbLfBL3X7Eu3nm2YDJw0b/ZSZ3Fnl+9NZaCzX1vDDi7kZFwOhWuhy0x0XsVRNlYTJLaS+i+JERuaFSvXdZj5zXGTqWeRQHAgkTjtmaHd7PAUy26dEO36l2MBDG5hmSrt0r941VdKy58QZ7HEMJBWmFqbSkq5qcMIkFZSC/Ck0xtSqyAsaSp89ZTcsUcmNxj/kH0FLfqJ3V/k2CArnFkxQYRu4KMPwNfHf/BXY4LsA4iVKWn/sZ8DuohKVGo132ITVpLkvrMrWfMncpXz2ou50Gro6HMkJPPz/fQZ8+dhz9JHfiXpdc/LUFaTjRQATcyVvn8A/p/4nQ)不用新增 API 同样可以实现

**Comment by wuzeqingit** [comment]
> 参考[这个](https://wsfe.github.io/vue-tree/playground#eNqlVl1v2jAU/StWXgAJkhUqTWJQsa192B62aa32slRTllzAzHEs26FMiP++6ziEfDUrFCFi32Ofe3wEPuyd90K42xScqTPTEAsWaLjxOSGzHw8SgEyjQAdz3zEP3yHhGsI/wW8GJJLBapWPEiGy0YInEYwMonQgNW5bBzxicIuVe1NBBg/ZZ16pFU5VKKnQRIFOBWEBX+FOrXwHURqLRGqyJxKW5ECWMolJD/X2CsjqtMDiSS3BQ3iksYhrfB4mXGlS00HmpG+0DglsgesBmd+QvTk1XVrApRGZz+ekl53oqjewMLHrXSGz5y0sg5Tp/sBgB5/j+9jQ+IVdUHX/p0Hz7ZpqBtOCdmirNGqUwjVlkQQ+Jdl288opmjSnXTWyKtBCWaNto65yNBrU4UNl9j/ucTd3DT6Pe9LNXYPL3I/F+FR93vyKyHKPCnCR+eNu8xvwOQaNu81vwJcbVHG63KMCXGTQpNugBnyOQZNugxpwt0G2Ymdtd0FBdupRlM64C2pfiRLZq+8CZOhyuwV+udtmc4fbLfBL3X7Eu3nm2YDJw0b/ZSZ3Fnl+9NZaCzX1vDDi7kZFwOhWuhy0x0XsVRNlYTJLaS+i+JERuaFSvXdZj5zXGTqWeRQHAgkTjtmaHd7PAUy26dEO36l2MBDG5hmSrt0r941VdKy58QZ7HEMJBWmFqbSkq5qcMIkFZSC/Ck0xtSqyAsaSp89ZTcsUcmNxj/kH0FLfqJ3V/k2CArnFkxQYRu4KMPwNfHf/BXY4LsA4iVKWn/sZ8DuohKVGo132ITVpLkvrMrWfMncpXz2ou50Gro6HMkJPPz/fQZ8+dhz9JHfiXpdc/LUFaTjRQATcyVvn8A/p/4nQ)不用新增 API 同样可以实现

使用event.preventDefault();禁用拖拽，但是原本节点是展开的，会被自动收缩
