### ISSUE TITLE
Unable to install this plugin

### ISSUE THREAD

**Issue by mypkq** [wsfe/ctree#91]
**问题描述**
![image](https://github.com/wsfe/vue-tree/assets/26788690/9ac7aeac-448b-4722-b324-c7d521faa01d)

**组件版本**
 - Vue3
 - @wsfe/vue-tree

**Comment by ChuChencheng** [comment]
Please check your npm registry

**Comment by mypkq** [comment]
ok，found the solution
![image](https://github.com/wsfe/vue-tree/assets/26788690/e553a6e6-4b10-4f22-a63a-e53b532d7244)
