### ISSUE TITLE
移动端H5上下滑动树时超级卡顿，大概率滑不动，是否能优化下性能，对移动端友好些？

### ISSUE THREAD

**Issue by mypkq** [wsfe/ctree#93]
**问题描述**
手机上很难滑动树，希望能优化

**组件版本**
 - Vue3
 - @wsfe/vue-tree

**Comment by ChuChencheng** [comment]
之前没在移动端上测试过，有空我再看看

**Comment by ChuChencheng** [comment]
有复现示例么

**Comment by ChuChencheng** [comment]
我在手机上看[这个示例](https://wsfe.github.io/vue-tree/examples/performance.html#performance)滑动的话还行，就是向上滑到顶的时候，列表回弹效果会有白屏，是这个问题么

**Comment by ChuChencheng** [comment]
iOS 回弹白屏问题修复了 #104 
滑不动问题没有复现，有问题麻烦提供复现示例与运行环境等信息后再开个新的 issue 吧

@wsfe/vue-tree v4.1.1
