### ISSUE TITLE
能否增加清空某个节点的函数。

### ISSUE THREAD

**Issue by xtuer** [wsfe/ctree#97]
**问题描述**
能否增加清空某个节点的函数。
要清空某个节点，目前使用已经提供的 API `treeRef.value. remove(nodeId)` 在 for 循环里逐个删除，数据量小的时候问题不大，数据量几万后界面会卡住几十秒。

目前暂时的解决办法是把要清空的节点从它的 parent 里删除，然后重建一个同样的节点。

**组件版本**
 - Vue3
 - @wsfe/vue-tree

**Comment by ChuChencheng** [comment]
清空节点是指移除节点的所有子节点？

**Comment by xtuer** [comment]
> 清空节点是指移除节点的所有子节点？

是的。

**Comment by ChuChencheng** [comment]
https://wsfe.github.io/vue-tree/examples/node-manipulation.html#reload-children
