### ISSUE TITLE
显示连接线时如果是虚线能否添加修改虚线点位的密集度

### ISSUE THREAD

**Issue by Bore-TuDou** [wsfe/ctree#98]
**Bug 描述**
显示连接线时如果是虚线能否添加修改虚线点位的密集度

**复现步骤**
我们现在需要显示虚线但是虚线是那种很密集的虚线能否提供参数修改
**期望表现**

**实际表现**

**组件版本**
 - Vue: 
 - @wsfe/ctree: 
 - @wsfe/vue-tree: 
 - 其他可帮助复现的 npm 包名称及版本

**额外信息**
其他要补充的信息

**Comment by ChuChencheng** [comment]
能否具体描述一下要实现的效果，或者有没有设计图之类的？

**Comment by ChuChencheng** [comment]
https://wsfe.github.io/vue-tree/examples/tree.html#show-line
可以试试呢
